# Grafana configuration
grafana:
  # Add Loki as a data source
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy
      # Even with auth_enabled: false, Loki requires an org ID header
      # This is a known quirk - the value can be anything since auth is disabled
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "fake"

# Production options (commented out):
# Prometheus storage:
# prometheus:
#   prometheusSpec:
#     retention: 15d
#     storageSpec:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: fast
#           resources:
#             requests:
#               storage: 50Gi

# Alertmanager high availability:
# alertmanager:
#   alertmanagerSpec:
#     replicas: 3
